seqs = {"sequence_1":"CTCGCGTTGCAGGCCGGCGTGTCGCGCAACGACGTGTGGGGCCTGACGGGCAGGGAGGATCTCGGCGGCGCCAACTATGCGGTCTTTCGGCTCGAAAGCCAGTTCCAGACCTCCGACGGCGCGCTGACCGTGCCCGGCTC","sequence_2":"CTCGCGTTGCAGGCCGGCGTGTCGCGCAACGACGTGTGGGGCCTGACGGGCAGGGAGGATCTCGGCGGCGCCAACTATGCGGTCTTTCGGCTCGAAAGCCAGTTCCAGACCTCCGACGGCGCGCTGACCGTGCCCGGCTC","sequence_3":"TGCTGAAGCTGGCGCCGGAGGGGACCGACCTCGCCGCGCTGATCTTCTCCGGGCTGTACAACGTCGGGATCGGCGCGGGCGCGCTGATCGGCAACCATATCGCCGGCGACTTCGGGCTGCCGTGGATCAAAGCCAGTTCC"}
import operator

seqlen = 6
dna_dir = {}
for key in seqs:
	
	for i in range(len(seqs[key])-seqlen):
		repeat = seqs[key][i:i+seqlen]
		if repeat not in dna_dir:
			dna_dir[repeat] = 1
		else:
			dna_dir[repeat] += 1
print sorted(dna_dir.items(), key=operator.itemgetter(1),reverse=1)[0]
